### ISSUE TITLE
Google calendar backend

### ISSUE THREAD

**Issue by triumphvalley** [saunah/saunah-backend#39]
## Goal
- To manage sauna availability, bookings should be added to a Google Calendar
- Users will then see, before booking, if the sauna is still available at the intended time-slot
- It would probably be the easiest to have one Google Calendar per sauna

## Tasks
- [x] Provide a class / package that allows to easily insert a booking into a Google Calendar, presumably using [Google Calendar API for Java](https://developers.google.com/calendar/api/quickstart/java)
- [x] Return some sort of ID when the event is inserted into the event, such that a reference to the calendar entry can be stored into the database and found in the Google Calendar again later
- [x] Provide some method to update an event in the Google Calendar by passing the ID of the event
- [x] Provide some method to delete an event in the Google Calendar by passing the ID of the event
- [x] Make the class generic, such that it works for different calendars → as probably every sauna will have a different calendar, this should work for multiple calendars, probably by passing something like the ID of the calendar
